project:
  type: website
  output-dir: docs

website:
  title: "IndyUseR"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Meetup
        href: https://www.meetup.com/Indy-useR-Group/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



