---
title: "Discussion of 2018 plans"
slug: "jan2018"
date: 2018-01-16
---

We discussed plans for 2018 as a group. Below are notes from the discussion

## Ideas on content to cover in the meetups

* trivia
* short package intro and go through vignette with some extensions
* go through datasets from different industries

* people can ask questions (ask a few days before) so that they can be addressed during the meetup

* Topics of interest:
    + github
    + docker/rocker
    + setting up RStudio/Shiny in cloud (AWS, google cloud etc.)
    + Markdown/knitr

* Participate in hackathons

* What folks want from the group:
    + See different things
    + intro stuff

* Look to change location closer to downtown

* Plan couple of months ahead

* Have some pre-made content to fill periodically

* Feb:
    + Reticulate: 30 min Shankar
    + Review of Rstudio conf: 1h Will Landau

* March:
    + Intro topic (data basics) - Todd

* Somewhere: (Alex)
    + using R with SQL, dbi
    + Start to finish build your theme for ggplot
