---
title: "Reproducible workflows at scale with Drake - Will Landau"
slug: "oct2019"
date: 2019-10-15
---

## Abstract

Ambitious workflows in R, such as machine learning analyses, can be difficult to manage. A single round of computation can take several hours to complete, and routine updates to the code and data tend to invalidate hard-earned results. You can enhance the maintainability, hygiene, speed, scale, and reproducibility of such projects with the drake R package. drake resolves the dependency structure of your analysis pipeline, skips tasks that are already up to date, executes the rest with optional distributed computing, and organizes the output so you rarely have to think about data files. This talk demonstrates how to create and maintain a realistic machine learning project using drake-powered automation.

*Links*:

1. Slides presented at the meetup ([link](https://wlandau.github.io/learndrake/))
2. Workshop materials to learn Drake ([link](https://github.com/wlandau/learndrake))



